// layout.js
import { JetBrains_Mono, Borel } from "next/font/google";
import "./globals.css";

// Components
import Header from "./../components/Header";
import PageTransition from "./../components/PageTransition";
import StairTransition from "./../components/StairTransition";
import grainImage from "./../../public/assets/images/grain.jpg";

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrainsMono",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

const borel = Borel({
  variable: "--font-borel",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata = {
  title: "Seif's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${jetbrainsMono.variable} ${borel.variable} antialiased min-h-screen relative`}
      >
        {/* Grain texture overlay */}
        <div
          className="absolute inset-0 -z-30 opacity-5"
          style={{
            backgroundImage: `url(${grainImage.src})`,
            backgroundBlendMode: "soft-light",
            backgroundRepeat: "repeat",
          }}
        ></div>

        {/* Main content */}
        <Header />
        <StairTransition />
        <PageTransition>{children}</PageTransition>
      </body>
    </html>
  );
}
